version: '3.8'

services:
  medical-chatbot:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PORT=8080
    volumes:
      - ./Data:/app/Data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
