services:
  - type: web
    name: healthmate-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PINECONE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
